/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as AccountOrdersRouteImport } from './routes/account/orders'
import { Route as AdminAdminManagementRouteImport } from './routes/admin/admin-management'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminSetupRouteImport } from './routes/admin/setup'
import { Route as OrderOrderNumberRouteImport } from './routes/order.$orderNumber'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AdminInvoiceOrderIdRouteImport } from './routes/admin/invoice.$orderId'
import { Route as AccountOrdersOrderNumberInvoiceRouteImport } from './routes/account/orders.$orderNumber.invoice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AdminAdminManagementRoute = AdminAdminManagementRouteImport.update({
  id: '/admin-management',
  path: '/admin-management',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AdminRouteRoute,
} as any)
const OrderOrderNumberRoute = OrderOrderNumberRouteImport.update({
  id: '/order/$orderNumber',
  path: '/order/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvoiceOrderIdRoute = AdminInvoiceOrderIdRouteImport.update({
  id: '/invoice/$orderId',
  path: '/invoice/$orderId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountOrdersOrderNumberInvoiceRoute =
  AccountOrdersOrderNumberInvoiceRouteImport.update({
    id: '/$orderNumber/invoice',
    path: '/$orderNumber/invoice',
    getParentRoute: () => AccountOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/admin/admin-management': typeof AdminAdminManagementRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/invoice/$orderId': typeof AdminInvoiceOrderIdRoute
  '/account/orders/$orderNumber/invoice': typeof AccountOrdersOrderNumberInvoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/admin/admin-management': typeof AdminAdminManagementRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/invoice/$orderId': typeof AdminInvoiceOrderIdRoute
  '/account/orders/$orderNumber/invoice': typeof AccountOrdersOrderNumberInvoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/admin/admin-management': typeof AdminAdminManagementRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/invoice/$orderId': typeof AdminInvoiceOrderIdRoute
  '/account/orders/$orderNumber/invoice': typeof AccountOrdersOrderNumberInvoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/account'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/shop'
    | '/account/orders'
    | '/admin/admin-management'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/setup'
    | '/order/$orderNumber'
    | '/product/$slug'
    | '/admin/invoice/$orderId'
    | '/account/orders/$orderNumber/invoice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/account'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/shop'
    | '/account/orders'
    | '/admin/admin-management'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/setup'
    | '/order/$orderNumber'
    | '/product/$slug'
    | '/admin/invoice/$orderId'
    | '/account/orders/$orderNumber/invoice'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/account'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/shop'
    | '/account/orders'
    | '/admin/admin-management'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/setup'
    | '/order/$orderNumber'
    | '/product/$slug'
    | '/admin/invoice/$orderId'
    | '/account/orders/$orderNumber/invoice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AccountRoute: typeof AccountRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopRoute: typeof ShopRoute
  OrderOrderNumberRoute: typeof OrderOrderNumberRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/admin-management': {
      id: '/admin/admin-management'
      path: '/admin-management'
      fullPath: '/admin/admin-management'
      preLoaderRoute: typeof AdminAdminManagementRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/order/$orderNumber': {
      id: '/order/$orderNumber'
      path: '/order/$orderNumber'
      fullPath: '/order/$orderNumber'
      preLoaderRoute: typeof OrderOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invoice/$orderId': {
      id: '/admin/invoice/$orderId'
      path: '/invoice/$orderId'
      fullPath: '/admin/invoice/$orderId'
      preLoaderRoute: typeof AdminInvoiceOrderIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/orders/$orderNumber/invoice': {
      id: '/account/orders/$orderNumber/invoice'
      path: '/$orderNumber/invoice'
      fullPath: '/account/orders/$orderNumber/invoice'
      preLoaderRoute: typeof AccountOrdersOrderNumberInvoiceRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdminManagementRoute: typeof AdminAdminManagementRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminInvoiceOrderIdRoute: typeof AdminInvoiceOrderIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminManagementRoute: AdminAdminManagementRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminInvoiceOrderIdRoute: AdminInvoiceOrderIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AccountOrdersRouteChildren {
  AccountOrdersOrderNumberInvoiceRoute: typeof AccountOrdersOrderNumberInvoiceRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersOrderNumberInvoiceRoute: AccountOrdersOrderNumberInvoiceRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

interface AccountRouteChildren {
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AccountRoute: AccountRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopRoute: ShopRoute,
  OrderOrderNumberRoute: OrderOrderNumberRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
